insert into Books (book_id, name, genre) values ('99-909-1235', 'That''s Life', 'Comedy');
insert into Books (book_id, name, genre) values ('41-012-5035', 'Katatsumori', 'Documentary');
insert into Books (book_id, name, genre) values ('62-634-8737', 'Love That Boy', 'Comedy|Romance');
insert into Books (book_id, name, genre) values ('81-562-9060', 'Voyager (Homo Faber)', 'Drama');
insert into Books (book_id, name, genre) values ('32-812-2899', 'Bait', 'Action|Horror|Thriller');
insert into Books (book_id, name, genre) values ('90-283-6010', 'Adventure in Space and Time, An', 'Drama');
insert into Books (book_id, name, genre) values ('04-807-9224', 'The Snow Woman', 'Fantasy|Horror');
insert into Books (book_id, name, genre) values ('73-618-3349', 'This Time Around', 'Comedy|Romance');
insert into Books (book_id, name, genre) values ('94-606-2371', 'Pool Without Water, A (Mizu no nai puuru)', 'Crime|Drama');
insert into Books (book_id, name, genre) values ('62-290-8828', 'Times and Winds (Bes vakit)', 'Drama');
insert into Books (book_id, name, genre) values ('90-401-7074', 'Purple Butterfly (Zi hudie)', 'Drama');
insert into Books (book_id, name, genre) values ('51-970-9160', 'Late Chrysanthemums (Bangiku)', 'Drama');
insert into Books (book_id, name, genre) values ('01-013-6483', 'Invitation to Happiness', 'Drama|Romance');
insert into Books (book_id, name, genre) values ('88-167-4336', 'The Baker''s Wife', 'Comedy|Drama');
insert into Books (book_id, name, genre) values ('40-845-5384', 'Clink of Ice, The (a.k.a.: Sound of Ice Cubes, The) (Le bruit des glaçons)', 'Comedy|Drama');
insert into Books (book_id, name, genre) values ('08-639-6529', 'Starsky & Hutch', 'Action|Comedy|Crime|Thriller');
insert into Books (book_id, name, genre) values ('58-247-6115', 'Method, The (Método, El)', 'Drama');
insert into Books (book_id, name, genre) values ('84-150-8274', 'HealtH', 'Comedy');
insert into Books (book_id, name, genre) values ('99-918-3338', 'Storm Warriors, The (Fung wan II)', 'Action|Adventure|Fantasy');
insert into Books (book_id, name, genre) values ('70-680-0515', 'Bohème, La', 'Drama|Romance');
insert into Books (book_id, name, genre) values ('23-615-2210', 'Dr. Jekyll and Mr. Hyde', 'Drama|Horror|Sci-Fi');
insert into Books (book_id, name, genre) values ('50-900-9259', 'What Price Glory', 'Comedy|Drama|War');
insert into Books (book_id, name, genre) values ('03-949-3632', 'Luther the Geek', 'Horror');
insert into Books (book_id, name, genre) values ('02-232-0655', 'Mannequin 2: On the Move', 'Comedy|Fantasy|Romance');
insert into Books (book_id, name, genre) values ('88-858-7953', 'Snow Queen', 'Adventure|Children|Fantasy');
insert into Books (book_id, name, genre) values ('62-301-0830', 'Startup.com', 'Documentary');
insert into Books (book_id, name, genre) values ('62-118-2972', 'Naked Weapon (Chek law dak gung)', 'Action|Drama|Romance|Thriller');
insert into Books (book_id, name, genre) values ('34-376-1657', 'Bohemian Life, The (La vie de bohème)', 'Comedy|Drama');
insert into Books (book_id, name, genre) values ('40-986-7421', 'Rugrats in Paris: The Movie', 'Animation|Children|Comedy');
insert into Books (book_id, name, genre) values ('56-937-8573', 'Dreaming of Joseph Lees', 'Drama|Romance');
insert into Books (book_id, name, genre) values ('26-787-4980', 'Angel in My Pocket', 'Comedy');
insert into Books (book_id, name, genre) values ('66-218-1904', 'The Next Voice You Hear....', 'Drama');
insert into Books (book_id, name, genre) values ('66-190-0736', 'One Man Band', 'Animation|Comedy|Musical');
insert into Books (book_id, name, genre) values ('29-623-6640', 'Last Minute, The', 'Drama|Mystery|Thriller');
insert into Books (book_id, name, genre) values ('61-230-7169', 'Ferryman, The', 'Fantasy|Horror|Thriller');
insert into Books (book_id, name, genre) values ('62-028-9865', 'Road, The', 'Crime|Drama|Horror|Thriller');
insert into Books (book_id, name, genre) values ('63-155-0357', 'Black Dynamite', 'Action|Comedy');
insert into Books (book_id, name, genre) values ('38-882-7741', 'Johnny Skidmarks', 'Crime|Drama|Mystery|Thriller');
insert into Books (book_id, name, genre) values ('50-594-6623', 'Russian Specialist, The (Mechanik, The)', 'Action|Drama|Thriller');
insert into Books (book_id, name, genre) values ('42-537-2709', 'It''s A Wonderful World', 'Comedy|Crime|Romance');
insert into Books (book_id, name, genre) values ('04-115-1268', 'Danger: Diabolik (Diabolik)', 'Action|Crime|Thriller');
insert into Books (book_id, name, genre) values ('25-301-2691', 'Latitude Zero (Ido zero daisakusen)', 'Action|Adventure|Sci-Fi');
insert into Books (book_id, name, genre) values ('72-778-4267', 'Restraint', 'Drama|Thriller');
insert into Books (book_id, name, genre) values ('67-875-1529', 'Last Will of Dr. Mabuse, The (Testament du Dr. Mabuse, Le)', 'Crime|Horror|Mystery');
insert into Books (book_id, name, genre) values ('66-214-6663', 'Invisible Circus, The', 'Drama|Romance');
insert into Books (book_id, name, genre) values ('40-217-3316', 'Miss Sadie Thompson', 'Drama|Musical|Romance');
insert into Books (book_id, name, genre) values ('09-499-5721', 'Badman''s Territory', 'Action|Drama|Western');
insert into Books (book_id, name, genre) values ('13-568-9971', 'Four Days in July', 'Comedy|Drama');
insert into Books (book_id, name, genre) values ('53-936-9969', 'You Will Be My Son (Tu seras mon fils)', 'Drama');
insert into Books (book_id, name, genre) values ('26-098-5712', 'My Gun is Quick', 'Mystery');
insert into Books (book_id, name, genre) values ('83-508-7445', 'Elia Kazan: A Director''s Journey', 'Documentary');
insert into Books (book_id, name, genre) values ('74-789-5269', 'You Got Served', 'Drama|Musical');
insert into Books (book_id, name, genre) values ('76-384-9346', 'Silent House, The (La casa muda)', 'Horror|Thriller');
insert into Books (book_id, name, genre) values ('74-866-8862', 'Quiller Memorandum, The', 'Action|Drama|Mystery|Thriller');
insert into Books (book_id, name, genre) values ('81-326-4788', 'Hook', 'Adventure|Comedy|Fantasy');
insert into Books (book_id, name, genre) values ('40-943-5223', 'Unsaid, The', 'Crime|Drama|Mystery');
insert into Books (book_id, name, genre) values ('54-630-1711', '9 Souls (Nain souruzu)', 'Drama');
insert into Books (book_id, name, genre) values ('71-461-1610', 'Hopscotch', 'Comedy');
insert into Books (book_id, name, genre) values ('06-002-3432', 'Cigarette Girl of Mosselprom, The (Papirosnitsa ot Mosselproma)', 'Comedy|Romance');
insert into Books (book_id, name, genre) values ('69-546-8790', 'Rocky Saga: Going the Distance, The', 'Documentary');
insert into Books (book_id, name, genre) values ('24-018-7140', 'Spend It All', 'Documentary');
insert into Books (book_id, name, genre) values ('45-247-8486', 'Brokedown Palace', 'Drama');
insert into Books (book_id, name, genre) values ('57-047-0422', 'Carry on Behind', 'Comedy');
insert into Books (book_id, name, genre) values ('95-878-6047', 'Boiling Point (3-4 x jûgatsu)', 'Action|Comedy|Crime');
insert into Books (book_id, name, genre) values ('29-675-7838', 'Women on the Verge of a Nervous Breakdown (Mujeres al borde de un ataque de nervios)', 'Comedy|Drama');
insert into Books (book_id, name, genre) values ('29-775-3666', 'Aces High', 'Action|Drama|War');
insert into Books (book_id, name, genre) values ('27-530-6652', 'Bad Seed, The', 'Drama|Thriller');
insert into Books (book_id, name, genre) values ('27-465-8941', 'Heartbreak Hotel', 'Comedy');
insert into Books (book_id, name, genre) values ('78-241-3199', 'Felicia''s Journey', 'Thriller');
insert into Books (book_id, name, genre) values ('94-055-2196', 'Cobra Verde', 'Adventure|Drama');
insert into Books (book_id, name, genre) values ('37-657-0231', 'Suspect', 'Crime|Drama|Thriller');
insert into Books (book_id, name, genre) values ('53-033-1621', 'Now You See Him, Now You Don''t', 'Comedy|Sci-Fi');
insert into Books (book_id, name, genre) values ('70-287-9997', 'Still Breathing', 'Comedy|Romance');
insert into Books (book_id, name, genre) values ('47-022-5674', 'Tobacco Road', 'Comedy|Drama');
insert into Books (book_id, name, genre) values ('90-034-0084', 'Wind Rises, The (Kaze tachinu)', 'Animation|Drama|Romance');
insert into Books (book_id, name, genre) values ('04-324-8253', 'On His Own (a.k.a. My Apprenticeship) (V lyudyakh)', 'Drama');
insert into Books (book_id, name, genre) values ('31-028-3023', 'In July (Im Juli)', 'Comedy|Romance');
insert into Books (book_id, name, genre) values ('89-919-1966', 'Funny About Love', 'Comedy|Romance');
insert into Books (book_id, name, genre) values ('64-565-6897', 'Russia House, The', 'Drama|Thriller');
insert into Books (book_id, name, genre) values ('39-650-7789', 'Precious Find', 'Action|Sci-Fi');
insert into Books (book_id, name, genre) values ('70-301-9666', '21 tapaa pilata avioliitto', 'Comedy|Romance');
insert into Books (book_id, name, genre) values ('92-038-9796', 'Adam and Eve (Adão e Eva)', 'Drama');
insert into Books (book_id, name, genre) values ('76-665-3049', 'Even the Rain (También la lluvia)', 'Drama');
insert into Books (book_id, name, genre) values ('91-965-5752', 'Quest for Camelot', 'Adventure|Animation|Children|Fantasy|Musical');
insert into Books (book_id, name, genre) values ('56-803-7552', 'Genevieve', 'Comedy');
insert into Books (book_id, name, genre) values ('24-003-7162', 'Scary Movie 4', 'Comedy|Horror');
insert into Books (book_id, name, genre) values ('18-917-6865', 'Anna: 6-18 (Anna: Ot shesti do vosemnadtsati)', 'Documentary');
insert into Books (book_id, name, genre) values ('40-455-5885', 'Wild Seven', 'Crime|Drama');
insert into Books (book_id, name, genre) values ('09-535-9487', 'Karan Arjun', 'Drama');
insert into Books (book_id, name, genre) values ('01-522-3377', 'A Cinderella Story: Once Upon a Song', 'Children|Comedy|Romance');
insert into Books (book_id, name, genre) values ('14-961-1195', 'Bad Blood (Mauvais sang)', 'Crime|Drama|Romance');
insert into Books (book_id, name, genre) values ('02-916-3048', 'Ballad of the Paper Balloons (a.k.a. Humanity and Paper Balloons) (Ninjô kami fûsen)', 'Drama');
insert into Books (book_id, name, genre) values ('19-552-9389', 'Fever', 'Drama');
insert into Books (book_id, name, genre) values ('44-619-4612', 'Smashing Time', 'Comedy');
insert into Books (book_id, name, genre) values ('19-809-4614', 'Fatal Hour, The', 'Crime|Mystery|Thriller');
insert into Books (book_id, name, genre) values ('67-681-4188', 'Guilty (Présumé coupable)', 'Drama');
insert into Books (book_id, name, genre) values ('96-084-9827', 'Stars in Shorts', 'Comedy');
insert into Books (book_id, name, genre) values ('15-901-1081', 'Married to It', 'Comedy|Drama');
insert into Books (book_id, name, genre) values ('63-803-5886', 'Three Stooges in Orbit, The', 'Comedy|Sci-Fi');
insert into Books (book_id, name, genre) values ('22-455-8683', 'Arcade', 'Horror|Sci-Fi');
